### ISSUE TITLE
Error while trying to load the gem 'turbolinks'

### ISSUE THREAD

**Issue by excpt** [turbolinks/turbolinks#16]
Hi,

I just ran into a problem when using the 5.0.0.beta.1 in combination with an middleman project. Is this a gem-related problem or do I have to contact the middleman team?

Edit: I'm using ruby 2.3.0p0 with rubygems 2.5.2.

```bash
excpt$ bundle exec middleman
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'turbolinks'. (Bundler::GemRequireError)
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.1/lib/middleman-core/load_paths.rb:33:in `setup_bundler'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.1/bin/middleman:10:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/bin/middleman:22:in `load'
	from /usr/local/var/rbenv/versions/2.3.0/bin/middleman:22:in `<main>'
```

Gemfile:

```ruby
source 'https://rubygems.org'

gem 'middleman', '~> 4.0'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-imageoptim'

gem 'nokogiri'

gem 'turbolinks', '~> 5.0.0.beta'
```

Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.5.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    backports (3.6.8)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (0.9.2)
    contracts (0.12.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.0.9.1)
    execjs (2.6.0)
    exifr (1.2.4)
    fast_blank (1.0.0)
    fastimage (1.8.1)
      addressable (~> 2.3, >= 2.3.5)
    ffi (1.9.10)
    fspath (2.1.1)
    haml (4.0.7)
      tilt
    hamster (2.0.0)
      concurrent-ruby (~> 0.8)
    hashie (3.4.3)
    htmlcompressor (0.2.0)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    image_optim (0.20.2)
      exifr (~> 1.1, >= 1.1.3)
      fspath (~> 2.1)
      image_size (~> 1.3)
      in_threads (~> 1.3)
      progress (~> 3.0, >= 3.0.1)
    image_optim_pack (0.2.1.20160119)
      fspath (~> 2.1)
      image_optim (~> 0.19)
    image_size (1.4.2)
    in_threads (1.3.1)
    json (1.8.3)
    kramdown (1.9.0)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    middleman (4.1.1)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.1)
      middleman-core (= 4.1.1)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.1.1)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.1)
      activesupport (~> 4.2)
      addressable (~> 2.4.0)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.12.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 1.8)
      hamster (~> 2.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      tilt (~> 1.4.1)
      uglifier (~> 2.6)
    middleman-imageoptim (0.2.1)
      image_optim (~> 0.20.2)
      image_optim_pack (~> 0.2.1)
      middleman-core (>= 3.1)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-minify-html (3.4.1)
      htmlcompressor (~> 0.2.0)
      middleman-core (>= 3.2)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2015.1120)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.1)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.1)
      tilt (~> 1.4.1)
    padrino-support (0.13.1)
      activesupport (>= 3.1)
    parallel (1.6.1)
    progress (3.1.1)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    sass (3.4.21)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    turbolinks (5.0.0.beta1)
      turbolinks-source
    turbolinks-source (5.0.0.beta1.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (~> 4.0)
  middleman-imageoptim
  middleman-livereload
  middleman-minify-html
  nokogiri
  turbolinks (~> 5.0.0.beta)

BUNDLED WITH
   1.11.2
```

**Comment by sstephenson** [comment]
The turbolinks gem is currently a Rails engine.

I haven’t used Middleman, but it looks like you can add the `turbolinks-source` gem to your Gemfile and add its asset path like so:

```ruby
ready do
  sprockets.append_path(Turbolinks::Source.asset_path)
end
```

**Comment by excpt** [comment]
Thanks @sstephenson! Works fine now. +1
