### ISSUE TITLE
undefined method `get?' for 302:Integer

### ISSUE THREAD

**Issue by coorasse** [turbolinks/turbolinks#389]
This issue has been reported on stackoverflow and I see that it has not yet been addressed:

https://stackoverflow.com/questions/49294119/undefined-method-get-for-302integer

From SO:

```ruby
describe 'DELETE /salesman/:id' do
  let!(:salesman) { create :salesman }
  subject(:request) do
    delete salesman_path(salesman), headers: auth_headers
  end

  it 'redirects to index' do
    expect(request).to redirect_to company_salesmen_path(salesman.company)
  end
end
```

```
Failure/Error: expect(request).to redirect_to company_salesmen_path(salesman.company)

NoMethodError:
    undefined method `get?' for 302:Integer
  # /Users/dennish/.rvm/gems/ruby-2.5.0/gems/turbolinks-5.1.0/lib/turbolinks/assertions.rb:37:in `turbolinks_request?'
  # /Users/dennish/.rvm/gems/ruby-2.5.0/gems/turbolinks-5.1.0/lib/turbolinks/assertions.rb:6:in `assert_redirected_to'
  # ./spec/requests/salesmen_spec.rb:206:in `block (3 levels) in <top (required)>'
```

**Comment by sstephenson** [comment]
Could you please [open an issue in the turbolinks-rails repository](https://github.com/turbolinks/turbolinks-rails/issues)? This repo is for the JavaScript library. Thanks!

**Comment by coorasse** [comment]
my bad: https://github.com/turbolinks/turbolinks-rails/issues/38
