### ISSUE TITLE
Turbolinks DOMException: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by ravitej177** [turbolinks/turbolinks#569]
I have been using the turbolinks through out the site. So, there are some 10 pages sharing the same layout which uses same javascript pack file i.e app.js, when I navigate through these pages in the website, one of the random pages getting broken without any reason.

Steps to reproduce the behavior(example behaviour)
1. Go to https://turbolinks-demo.glitch.me/
2. Click on ''Link A" then click on "Link B" and so.on
3. At random Link of nth page it is getting broken and throws the error

Turbolinks DOMException: Failed to execute 'removeChild' on 'Node'

Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at o.removeCurrentHeadProvisionalElements (http://lvh.me:3000/packs/js/elearning-94610cb36b0b0c55dc03.js:330849:44)
    at o.mergeHead (http://lvh.me:3000/packs/js/elearning-94610cb36b0b0c55dc03.js:330821:95)
    at o.render (http://lvh.me:3000/packs/js/elearning-94610cb36b0b0c55dc03.js:330815:46)
    at Function.e.render (http://lvh.me:3000/packs/js/elearning-94610cb36b0b0c55dc03.js:330775:57)

**Expected behavior**

**Details (please complete the following information):**
 - Operating System: [e.g. Ubuntu WSL2 , Windows]
 - Browser [e.g. Edge, Chrome]
 - Turbolinks Version [v5.2.0]

**Screenshots**
![Screenshot 2020-09-03 192101](https://user-images.githubusercontent.com/12657841/92123826-aac7c280-ee1a-11ea-8ff8-b0c3cca89a8f.jpg)

**Comment by joker-777** [comment]
Interesting, we are seeing this error also a lot but couldn't figure out why. How did you reproduce it and how did you fix it eventually?

**Comment by ravitej177** [comment]
This happens when there is google tag manager or any dynamic script blocks in the head block. 

Moving those script blocks to the first fold of the body tag resolved the error.

**Comment by joker-777** [comment]
My problem is that I can't reproduce it. I can see in our js error tracking system that lots of people who use our website have this error but until now I haven't been able to reproduce it myself. We do use google tag manager though and we also add lots of scripts dynamically to the `head` for example via dynamic imports.

**Comment by ravitej177** [comment]
To reproduce, you have navigate through pages which have same layout (or) same js content in the head, so after 1 or 2 mins when the js gets refreshed, you will get the error, when you navigate between the pages.

**Comment by joker-777** [comment]
Hmm, I'm not sure I understand. Why should the js gets refreshed after 1 or 2 minutes?
