### ISSUE TITLE
error Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '{$nonce}' is not a valid attribute name

### ISSUE THREAD

**Issue by samehdoush** [turbolinks/turbolinks#613]
**Describe the bug**
laravel 8
livewire 2
turbolinks 5.2

```
turbolinks.min.js:9 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '{$nonce}' is not a valid attribute name.
    at r (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:16771)
    at o.e.createScriptElement (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:16644)
    at o.copyNewHeadScriptElements (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:18617)
    at o.mergeHead (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:17652)
    at o.render (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:17404)
    at Function.e.render (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:16240)
    at t.renderSnapshot (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:22767)
    at t.render (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:22485)
    at r.render (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:10:755)
    at r.<anonymous> (https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js:9:27157)
```

**To Reproduce**
demo : https://newtest.minifatura.com/en

1. Go to ' https://newtest.minifatura.com/en'
2. Click on 'Cart' or Account -> login or register
3. See error

**Expected behavior**
in head tag : 
 ```
   @livewireScripts

 

    <script src="https://cdn.jsdelivr.net/npm/turbolinks@5.2.0/dist/turbolinks.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/livewire/turbolinks@v0.1.x/dist/livewire-turbolinks.js"
        data-turbolinks-eval="false" data-turbo-eval="false"></script>
   
```

**Details (please complete the following information):**
 - Operating System: Windows 10
 - Browser edge
 - Turbolinks Version v5.2.0
 - laravel Version v8
- livewire Version v2

**Comment by samehdoush** [comment]
I found the problem was due to cloudflare
I turned off the Rocket Loader feature
And it works fine
